apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: level5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # Init container to clone the repository and copy the index.html to the volume
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        command: 
          - /bin/sh
          - -c
          - |
            git clone https://github.com/MohamdShehata/DevOps.git /tmp/repo
            cp /tmp/repo/index.html /mnt/html/index.html
        volumeMounts:
        - name: nginx-html
          mountPath: /mnt/html

      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html

      volumes:
      - name: nginx-html
        persistentVolumeClaim:
          claimName: nginx-pvc
